### ISSUE TITLE
Problème affichage sur Chrome

### ISSUE THREAD

**Issue by thomasmagninfeysot** [Georiviere/Georiviere-public#47]
Problème d'affichage de la carte sur Chrome (reproduit sur plusieurs ordis), les cours d'eaux "clignotent"
![Animation](https://github.com/Georiviere/Georiviere-public/assets/19687397/3a68b677-8c4f-4352-8472-df2c42219037)

**Comment by dtrucs** [comment]
Effectivement je reproduis.
J'ai regardé et je pense que c'est le système d'animation de cours d'eau qui met à genoux la tâche chrome.
En désactivant l'accélération matériel de chrome (en se rendant sur l'url `chrome://settings/?search=mat%C3%A9rielle`), la map ne clignote plus (mais accuse d'un bon lag).

Une solution serait de désactiver cette animation car couplé à votre volume de donnée (steam.json fait 1.5mo) présente déjà des limites

**Comment by dtrucs** [comment]
Cet issue confirme https://github.com/rubenspgcavalcante/leaflet-ant-path/issues/137

**Comment by thomaspnrhj** [comment]
ok pour désactiver car entre la longueur d'affichage et les soucis sur Chrome, est-ce que tu peux donner la marche à suivre à @xavyeah39 pour désactiver et voir si ça améliore la vitesse d’affichage notamment ?

**Comment by dtrucs** [comment]
Ça ne sera pas possible via une configuration, il y a une condition dans le code pour appliquer l'animation des flux de rivière.
Du dev est nécessaire. On va réfléchir avec @babastienne s'il y a moyen de régler ce problème de lenteur ou carrément retirer l'animation.

**Comment by thomasmagninfeysot** [comment]
Hello @xavyeah39 il y une nouvelle version qui corrige le bug d'affichage, surement voir avec Aymeric pour une MAJ ! Tcho

**Comment by xavyeah39** [comment]
La mise à jour est faite pour le Haut-Jura et on confirme le fix.
Merci !!
